name: SourceField GitHub Workflow

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  parseAndMap:
    name: Parse and Map repo
    runs-on: ubuntu-latest
    steps:
      - name: Do it all
        uses: ./action.yml
        with:
          who-to-greet: "You"
