name: SourceField GitHub Workflow

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  parseAndMap:
    name: Parse and Map repo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Do it all
        uses: .
        with:
          who-to-greet: "You"
